pipeline {
    agent any
    stages {
        stages('Build'){
            steps {
                echo "Etapa de build no disponible"
        }
        }
        stages('Test'){
            steps {
                echo "Etapa de test no disponible"
        }
    }
    stage('Desploy'){
        steps {
            sh "docker-compose down -v"
            sh "docker-compose up -d --build "
        }
    }
    post {
        always{
            cleanWs()
        }
    }
}
}